#Example1
-
  name: 'Execute a script on all web server nodes'
  hosts: all_servers
  tasks:
    -
      service: 'name=mysql state=started'
      when: 'ansible_host=="server4.company.com"'

#Example2
-
  name: 'Am I an Adult or a Child?'
  hosts: localhost
  vars:
    age: 25
  tasks:
    -
      command: 'echo "I am a Child"'
      when: age<18
    -
      command: 'echo "I am an Adult"'
      when: age>=18

#Example3
-
  name: 'Add name server entry if not already entered'
  hosts: localhost
  tasks:
    -
      shell: 'cat /etc/resolv.conf'
      register: command_output #store the output of above command in command_output variable
    -
      shell: 'echo "nameserver 10.0.250.10" >> /etc/resolv.conf'
      when: command_output.stdout.find('10.0.250.10') == -1 # stdout used to access the file and find respective data