#Example-1
-
  name: 'Update nameserver entry into resolv.conf file on localhost'
  hosts: localhost
  tasks:
    -
      name: 'Update nameserver entry into resolv.conf file'
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{nameserver_ip}}'

#Example-2
-
  name: 'Update nameserver entry into resolv.conf file on localhost'
  hosts: localhost
  tasks:
    -
      name: 'Update nameserver entry into resolv.conf file'
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{ nameserver_ip }}'
    -
      name: 'Disable SNMP Port'
      firewalld:
        port: '{{snmp_port}}'
        permanent: true
        state: disabled


#example 3 - declaring variables in playbook

-
  name: 'Update nameserver entry into resolv.conf file on localhost'
  hosts: localhost
  tasks:
    -
      name: 'Print my car model'
      command: 'echo "My car''s model is {{car_model}} "'
    -
      name: 'Print my country'
      command: 'echo "I live in the {{country_name}}"'
    -
      name: 'Print my title'
      command: 'echo "I work as a {{title}}"'


  vars: #you will need to declare variables under this section

    car_model: BMW M3
    country_name: USA
    title: Systems Engineer
