apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteMany #this mode should match with the persistent volume
  resources:
    requests:
      storage: 50Mi
  storageClassName: manual